<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function createQuery($word, $field)
    {
        $repository = $this->getDoctrine()->getRepository('AppBundle:User');
        $field = array('user', 'password', 'id');
        $word = '';

        $query = $repository->createQueryBuilder('u')
            ->where('u.$field == :$field')
            ->setParameter('plz', '1')
            ->orderBy('p.plz', 'ASC')
            ->getQuery();

        $users = $query->getResult();
        print_r($users);die;
        // to get just one result:
        // $product = $query->setMaxResults(1)->getOneOrNullResult();
    }
}
